### ISSUE TITLE
Slack interactive messages

### ISSUE THREAD

**Issue by d-kononov** [go-joe/joe#24]
Do you have any plans to add [slack interactive message](https://api.slack.com/interactive-messages) and [dialogs](https://api.slack.com/dialogs) features?

**Comment by fgrosse** [comment]
Hey @d-kononov , this request is in its nature a bit similar to #21 . I am mostly hesitant to integrate a feature that is very specific to the feature set of a single adapter (slack in this case).

It could be we can find a good abstraction that allows us to integrate such a feature directly in Joe. Until then you can deal with this by having a slack client directly available as field in your own bot type (details see https://github.com/go-joe/joe/issues/21#issuecomment-530082484).

Please feel free to suggest a design that offers the necessary abstraction on top of adapters without adding to much complexity or opinions that are just hard to translate to other adapters. Maybe we could also treat this as some sort of new joe Module that allows to opt-in to specific features of an adapter but I need more time to think about a clean design :)

**Comment by robertgzr** [comment]
What do you think about an adapter extension that simply returns the underlying adapter type?

```go
type ReflectingAdapter interface {
	Self() interface{}
}

...

func (b Bot) MessageHandler(msg joe.Message) error {
	rfl, ok := b.Adapter.(ReflectingAdapter)
	if !ok {
		return joe.ErrNotImplemented
	}
	tg, _ := rfl.Self().(*TelegramAdapter)

	// do telegram specific stuff
}
```

This would allow for writing adapter specific message handlers with very little extra code for adapter implementations.
You could then just expose the client used in the adapter or provide helper methods to do stuff. 

Of course it would be nicer if you didn't have to check for the `ReflectingAdapter` interface, not sure how you feel about breaking the API for the 4 existing adapters to make `Self()` part of the `Adapter` interface @fgrosse

**Comment by fgrosse** [comment]
Can you explain why we would need the new interface to do the type check?

I.e. wouldn't this work equally well with the current state of things?

```
func (b Bot) MessageHandler(msg joe.Message) error {
	s, ok := b.Adapter.(*slack.BotAdapter)
	if !ok {
		return joe.ErrNotImplemented
	}

	// do slack specific stuff
	…
}
```

If you rely on very specific adapter API features I would actually encourage you to access them not through the adapter but just with the native client as a field on your custom bot type because it will give you maximum flexibility without having to ask the maintainer of the joe adapter to make every detail of the underlying API client available to you. 

This approach is described in https://github.com/go-joe/joe/issues/21#issuecomment-530082484 a bit.

**Comment by fgrosse** [comment]
I'm closing this issue since we now have documentation about this topic at https://joe-bot.net/recipes/slack/
