### ISSUE TITLE
Registering a default response when no match

### ISSUE THREAD

**Issue by jfchevrette** [go-joe/joe#25]
I've been trying to figure out how I can make my bot respond with a helpful message when no message is matched.

Naively I've tried the following approach which results in both handlers to be executed
```
b.Respond("foo", b.FooHandler)
b.Respond(".*", b.HelpHandler)
```

Unless I'm missing something, there does not seem to be a way to register a default handler that would only be executed if no other handler matches the message.

There also does not appear to be a way to stop processing handlers after the `FooHandler` is executed.

**Comment by fgrosse** [comment]
Hey there. I would treat the two issues you are describing separately.

### 1. There is no way to define a default handler when no other matches it

Its true that this is simply lacking at the moment. For me the use case so far did not really appear because I am using the bot in larger slack channels where normally none of the handlers would match anything the people are writing there and only occasionally they would send a message recognized by the bot who will otherwise silently listen.

I do however see a point in providing some functionality to implement this. Give me some time and I will try to come up with an implementation that I like. If somebody else wants to give it a shot then please propose a design as comment under this issue.

### 2. There is no way to stop processing when one handler has consumed the message

I think we should open a new issue for this to describe the use case and find a solution. It may be a bit tricky because it relies on the order of handlers which I am not sure out of the top of my head right now if that is actually defined. Also there is a danger of unexpected behavior when events may come from multiple modules. Its still an interesting feature though and worth discussing :)
